version: "3.3"

services:
  nginx:
    build:
      context: ./Frontend/lolmushroom
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/meshroom/S11P12A401/Frontend/lolmushroom/.env:/app/.env
      - /home/ubuntu/meshroom/S11P12A401/Frontend/lolmushroom/ssl:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - mesh_network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - mesh_network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mesh_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mesh_network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - /home/ubuntu/meshroom/S11P12A401/Backend/.env
    depends_on:
      - kafka
      - redis
    networks:
      - mesh_network

networks:
  mesh_network:
    driver: bridge
